// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrucoRPG.Infraestructura.Data;

#nullable disable

namespace TrucoRPG.Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("HeroeSeleccionadoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("HeroeSeleccionadoId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.Heroe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescripcionHabilidadActiva")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DescripcionHabilidadPasiva")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoHeroe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DescripcionHabilidadActiva = "Cada 3 manos, puede reemplazar una carta a eleccion de su mano por otra aleatoria del mazo. La nueva carta nunca puede ser de menor valor que la descartada.",
                            DescripcionHabilidadPasiva = "10% más de probabilidad de recibir carta de valor alto.",
                            Nombre = "Manipulador",
                            TipoHeroe = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DescripcionHabilidadActiva = "Debe activarse antes de comenzar la ronda. Si gana el truco, duplica los puntos de la ronda. Si pierde, el rival gana +2 puntos extra.",
                            DescripcionHabilidadPasiva = "El Timbero lanza una moneda:Cara → obtiene +1 punto. Cruz → no ocurre nada",
                            Nombre = "Timbero",
                            TipoHeroe = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DescripcionHabilidadActiva = "El próximo Truco / Retruco / Vale 4 o Envido cantado por el Fanfarrón vale +1 punto adicional si es aceptado.",
                            DescripcionHabilidadPasiva = "En caso de empate de envido, en vez de definirse el ganador por quien es mano, el Fanfarrón gana automáticamente el empate.",
                            Nombre = "Fanfarron",
                            TipoHeroe = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DescripcionHabilidadActiva = "Cada 2 manos revela UNA carta aleatoria del rival durante toda la ronda. Solo puede usarse al comienzo de la mano.",
                            DescripcionHabilidadPasiva = "El rival no puede ver cuándo El Mentiroso tiene habilidad disponible. Cuando usa su habilidad, el rival no recibe ninguna notificación visual.",
                            Nombre = "Mentiroso",
                            TipoHeroe = 3
                        });
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.ItemTienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("SpriteKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "HABILIDADES",
                            Descripcion = "Te otorga la habilidad del manipulador en una partida",
                            Img = "/assets/objetos/objeto.png",
                            Nombre = "BOLEADORAS",
                            Precio = 150
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "HABILIDADES",
                            Descripcion = "Te otorga la habilidad del timbero en una partida",
                            Img = "/assets/objetos/objeto.png",
                            Nombre = "BOLEADORAS",
                            Precio = 150
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "HABILIDADES",
                            Descripcion = "Te otorga la habilidad del fanfarron en una partida",
                            Img = "/assets/objetos/objeto.png",
                            Nombre = "BOLEADORAS",
                            Precio = 150
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "HABILIDADES",
                            Descripcion = "Te otorga la habilidad del mentiroso en una partida",
                            Img = "/assets/objetos/objeto.png",
                            Nombre = "BOLEADORAS",
                            Precio = 150
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "ARMARIO",
                            Descripcion = "Cambia el color de tu Poncho a rosa",
                            Img = "/assets/objetos/GotaRosa.png",
                            Nombre = "Poncho rosa",
                            Precio = 150,
                            SpriteKey = "personaje1rosa"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "ARMARIO",
                            Descripcion = "Cambia el color de tu Poncho a marrón",
                            Img = "/assets/objetos/GotaMarron.png",
                            Nombre = "Poncho marrón",
                            Precio = 150,
                            SpriteKey = "personaje1rosa"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "ARMARIO",
                            Descripcion = "Cambia el color de tu Poncho a rojo",
                            Img = "/assets/objetos/GotaRoja.png",
                            Nombre = "Poncho rojo",
                            Precio = 150,
                            SpriteKey = "personaje1rosa"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "ARMARIO",
                            Descripcion = "Cambia el color de tu Poncho a azul",
                            Img = "/assets/objetos/GotaAzul.png",
                            Nombre = "Poncho azul",
                            Precio = 150,
                            SpriteKey = "personaje1rosa"
                        });
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.ProgresoPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<int>("UltimoRivalDerrotadoNivel")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ProgresoPartida", (string)null);
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.Rival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DescripcionHabilidad")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreHabilidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoHabilidad")
                        .HasColumnType("int");

                    b.Property<int>("TipoRival")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .IsUnique();

                    b.ToTable("Rivales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Descripcion = "Primer jefe de la historia. Habita las orillas del lago.",
                            DescripcionHabilidad = "Cada 2 manos, cambia el palo de 2 cartas. Pasiva Remolino: 50% de cambiar el palo de tu primera carta en la 1.ª baza.",
                            Nivel = 1,
                            Nombre = "Nahuelito",
                            NombreHabilidad = "Salpicadura",
                            TipoHabilidad = 1,
                            TipoRival = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Descripcion = "Segundo jefe de la historia. Guarda la entrada de la cueva.",
                            DescripcionHabilidad = "Cada 2 manos, muestra tus cartas 5s y oculta 2. Pasiva Trampa del monte: +1 pt si nadie cantó envido ni truco.",
                            Nivel = 2,
                            Nombre = "El Pomberito",
                            NombreHabilidad = "Travesura",
                            TipoHabilidad = 2,
                            TipoRival = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Descripcion = "Tercer jefe de la historia. Acecha en las profundidades de la cueva.",
                            DescripcionHabilidad = "Rasguño: te cambia una carta aleatoria por una de menor valor (puede ocurrir en cualquier momento de la ronda).\nAullido: su aullido te asusta y te manda al mazo.",
                            Nivel = 3,
                            Nombre = "El Lobizón",
                            NombreHabilidad = "Rasguño",
                            TipoHabilidad = 3,
                            TipoRival = 3
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Descripcion = "Cuarto jefe de la historia. Una presencia luminosa que desorienta al viajero.",
                            DescripcionHabilidad = "Emite una luz radiante que te confunde y te hace jugar una carta al azar (puede ocurrir en cualquier momento de la ronda).",
                            Nivel = 4,
                            Nombre = "La Luz Mala",
                            NombreHabilidad = "Destello",
                            TipoHabilidad = 0,
                            TipoRival = 4
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Descripcion = "Jefe final de la historia. Domina el trono con tres fases de combate.",
                            DescripcionHabilidad = "Jefe final con 3 fases y distintas habilidades según los puntos que le quedan para ganar. (Próximamente.)",
                            Nivel = 5,
                            Nombre = "Mandinga",
                            NombreHabilidad = "Fases",
                            TipoHabilidad = 0,
                            TipoRival = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrucoRPG.Dominio.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrucoRPG.Dominio.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrucoRPG.Dominio.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrucoRPG.Dominio.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.ApplicationUser", b =>
                {
                    b.HasOne("TrucoRPG.Dominio.Entities.Heroe", "HeroeSeleccionado")
                        .WithMany()
                        .HasForeignKey("HeroeSeleccionadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeroeSeleccionado");
                });

            modelBuilder.Entity("TrucoRPG.Dominio.Entities.ProgresoPartida", b =>
                {
                    b.HasOne("TrucoRPG.Dominio.Entities.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
